version: '3'
services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - default
  mysql-db:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_DATABASE=martial_arts_meta_dev
      - MYSQL_PASSWORD=Metagame@2023
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
    command: --pid-file=/var/lib/mysql/mysqld.pid
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./angular-app/dist:/usr/share/nginx/html
    networks:
      - my-bridge-network
volumes:
  mysql-data:

networks:
  default:
  my-bridge-network:
    driver: bridge